### ISSUE TITLE
Can't get this mod to work on Linux

### ISSUE THREAD

**Issue by RadGH** [Scarabol/ColonyCommandsMod#3]
I'm running a Linux server (Ubuntu 18.04) and have the CS server running through a docker container (https://github.com/Didstopia/colony-survival-server).

I've added the mod to the mods folder, extracted appropriately so that I have:

/home/docker/colony-survival-server/colonysurvival_data/gamedata/mods/Scarabol/Commands

And I verified the files in the Commands folder within Docker:

```
$ docker exec colony-survival-server ls /steamcmd/colonysurvival/gamedata/mods/Scarabol/Commands
announcements.example.json
chatcolors.example.json
Commands.dll
modInfo.json
protection-ranges.example.json
```

But when I start my server the mod isn't loaded and doesn't show in the mod list of the game browser. Is there another step to load a mod? Is there an extra step when running the server from command line?

Also, I tried compiling the mod from source code using the make command. I received this error:

```
$ sudo make
mcs /target:library -r:../../../../colonyserver_Data/Managed/Assembly-CSharp.dll -r:../../Pipliz/APIProvider/APIProvider.dll -r:../../../../colonyserver_Data/Managed/UnityEngine.dll -out:"Commands.dll" -sdk:2 src/*.cs
src/ItemIdCommand.cs(27,60): error CS1644: Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification
Compilation failed: 1 error(s), 0 warnings
makefile:38: recipe for target 'default' failed
make: *** [default] Error 1
```

I'm not sure what this means, but I learned that "mcs" is installed via "mono-mcs". Is that incorrect? Is there something else required to build this?

Thanks

**Comment by RadGH** [comment]
Apparently it was just not compatible with 0.6.2.0, so I edited modinfo to change compatible version from 0.6.0 to 0.6.2 and it works now. Not sure if any bugs will come of it though.

**Comment by Dids** [comment]
This is still an issue, which begs the question if this mod is still being maintained? And if not, it might be worth adding more maintainers to it. :)

**Comment by Scarabol** [comment]
Hello! I do not maintain this mod anymore. Pls checkout this fork here: https://github.com/adrenalynn/ColonyCommandsMod

Changing the compatible version listing sometimes does the trick, but I strongly doubt that this will work for a longer period of time.

**Comment by Dids** [comment]
@Scarabol If possible, could you update the readme to mention that this is no longer maintained, and perhaps link to Adrenalynn's fork? This way everyone would know to go there first, instead of opening any issues here in the future. :)
